"""
モックサービス実装

パイプライン統合テスト用のモックサービス
"""

from typing import List, Optional
from pathlib import Path

from site2.core.domain.fetch_domain import WebsiteCache
from site2.core.domain.detect_domain import (
    MainContent,
    Navigation,
    DocumentOrder,
    NavigationStructure,
    NavLink,
    OrderedFile,
    DetectionScore,
)
from site2.core.domain.build_domain import MarkdownDocument, DocumentMetadata
from site2.core.ports.fetch_contracts import (
    FetchResult,
    FetchServiceProtocol,
    WebsiteCacheRepositoryProtocol,
)
from site2.core.ports.detect_contracts import DetectServiceProtocol
from site2.core.ports.build_contracts import BuildServiceProtocol


class MockRepository(WebsiteCacheRepositoryProtocol):
    """メモリ内でキャッシュを管理するモックリポジトリ"""

    def __init__(self):
        self._cache = {}

    async def save(self, cache: WebsiteCache) -> None:
        self._cache[str(cache.url.value)] = cache

    async def find_by_url(self, url: str) -> Optional[WebsiteCache]:
        return self._cache.get(url)

    async def list_all(self) -> List[WebsiteCache]:
        return list(self._cache.values())


class MockFetchService(FetchServiceProtocol):
    """simple-siteのデータを返すモックサービス"""

    def __init__(self, repository: WebsiteCacheRepositoryProtocol):
        self.repository = repository

    async def execute(self, url: str) -> FetchResult:
        """simple-siteのHTMLを読み込んで返す"""
        # テストフィクスチャのパス
        fixture_dir = (
            Path(__file__).parent.parent / "fixtures" / "websites" / "simple-site"
        )
        index_file = fixture_dir / "index.html"

        if not index_file.exists():
            raise FileNotFoundError(f"Test fixture not found: {index_file}")

        # HTMLファイルを読み込み
        html_content = index_file.read_text(encoding="utf-8")

        # FetchResultにhtml_contentを含める簡易実装
        # 実際のFetchResultに合わせて属性を追加
        result = FetchResult(
            cache_id="test-cache",
            root_url=url,
            pages_fetched=1,
            pages_updated=1,
            total_size=len(html_content.encode("utf-8")),
            cache_directory=str(fixture_dir),
        )

        # テスト用にhtml_contentを追加（動的属性）
        result._html_content = html_content

        return result


class MockDetectService(DetectServiceProtocol):
    """固定の検出結果を返すモックサービス"""

    async def detect_main_content(self, html: str) -> MainContent:
        """main.content セレクタを返す"""
        # HTMLから簡単なテキスト抽出
        text_content = (
            "Welcome to Test Site. This is a simple test site for site2 testing."
        )

        return MainContent(
            selector="main.content",
            html_content='<main class="content"><h1>Welcome to Test Site</h1><p>This is a simple test site for site2 testing.</p></main>',
            text_content=text_content,
            title="Welcome to Test Site",
            confidence=DetectionScore.high(),
        )

    async def detect_navigation(self, html: str) -> Navigation:
        """nav.navigation セレクタを返す"""
        # モックのナビゲーション構造を作成
        nav_links = [
            NavLink(text="Home", href="index.html", level=0),
            NavLink(text="About", href="about.html", level=0),
            NavLink(text="Guide", href="docs/guide.html", level=0),
        ]

        nav_structure = NavigationStructure(
            root_selector="nav.navigation", links=nav_links
        )

        return Navigation(
            selector="nav.navigation",
            structure=nav_structure,
            confidence=DetectionScore.high(),
        )

    async def detect_order(self, cache_dir: Path) -> DocumentOrder:
        """固定の順序を返す"""
        ordered_files = [
            OrderedFile(
                file_path=cache_dir / "index.html", title="Home", order=0, level=0
            ),
            OrderedFile(
                file_path=cache_dir / "about.html", title="About", order=1, level=0
            ),
            OrderedFile(
                file_path=cache_dir / "docs" / "guide.html",
                title="Guide",
                order=2,
                level=1,
            ),
        ]

        return DocumentOrder(
            files=ordered_files, method="navigation", confidence=DetectionScore.high()
        )


class MockBuildService(BuildServiceProtocol):
    """簡単なMarkdownを生成するモックサービス"""

    async def build_markdown(self, contents: List[MainContent]) -> MarkdownDocument:
        """シンプルなMarkdownを生成"""
        if not contents:
            raise ValueError("No content provided")

        # 最初のコンテンツからMarkdownを生成
        main_content = contents[0]

        markdown_content = f"""# {main_content.title or "Untitled"}

{main_content.text_content}

---

*Generated by MockBuildService*
"""

        metadata = DocumentMetadata(
            title=main_content.title or "Untitled",
            source_url="http://test-site",
            description="Generated from mock service",
        )

        return MarkdownDocument(
            title=main_content.title or "Untitled",
            content=markdown_content,
            metadata=metadata,
        )
